# Generated by Django 4.2.4 on 2023-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(default="", help_text="Your biography", null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(
                help_text="Your profession", max_length=100, null=True
            ),
        ),
    ]
